"""empty message

Revision ID: 0a6fc7010ab5
Revises: 41e71db0f817
Create Date: 2019-05-18 10:48:13.441912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a6fc7010ab5'
down_revision = '41e71db0f817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('banner', sa.String(length=100), nullable=False))
    op.alter_column('articles', 'content',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'content',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.drop_column('articles', 'banner')
    # ### end Alembic commands ###
