"""empty message

Revision ID: 7e25b6900e38
Revises: d31bec08efb9
Create Date: 2019-05-24 10:36:48.331898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e25b6900e38'
down_revision = 'd31bec08efb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'classification', ['cid'], ['cid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'cid')
    # ### end Alembic commands ###
