"""empty message

Revision ID: 9542db52afbc
Revises: e1575862a03c
Create Date: 2019-05-28 10:16:46.270527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9542db52afbc'
down_revision = 'e1575862a03c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wfhrj_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('is_login', sa.Integer(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_foreign_key(None, 'whfrj_products', 'whfrj_classification', ['cid'], ['cid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whfrj_products', type_='foreignkey')
    op.drop_table('wfhrj_admin')
    # ### end Alembic commands ###
