"""empty message

Revision ID: de0c068c2560
Revises: 90f2fb7bb8e1
Create Date: 2019-05-24 11:03:14.424618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de0c068c2560'
down_revision = '90f2fb7bb8e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whfrj_classification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('introduction', sa.String(length=50), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whfrj_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('id_pay', sa.Integer(), nullable=False),
    sa.Column('pay_time', sa.DateTime(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whfrj_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wxname', sa.String(length=20), nullable=False),
    sa.Column('truename', sa.String(length=5), nullable=True),
    sa.Column('tel', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whfrj_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('banner', sa.String(length=200), nullable=True),
    sa.Column('image_1', sa.String(length=200), nullable=True),
    sa.Column('image_2', sa.String(length=200), nullable=True),
    sa.Column('image_3', sa.String(length=200), nullable=True),
    sa.Column('vedio', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('line_price', sa.Float(), nullable=True),
    sa.Column('introduction', sa.String(length=50), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['whfrj_classification.cid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('id_pay', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('pay_time', mysql.DATETIME(), nullable=True),
    sa.Column('add_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.drop_table('whfrj_products')
    op.drop_table('whfrj_users')
    op.drop_table('whfrj_orders')
    op.drop_table('whfrj_classification')
    # ### end Alembic commands ###
