"""empty message

Revision ID: e1575862a03c
Revises: 
Create Date: 2019-05-27 09:09:03.046326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1575862a03c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wfhrj_wxtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=200), nullable=True),
    sa.Column('add_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('whfrj_products', sa.Column('specifications', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'whfrj_products', 'whfrj_classification', ['cid'], ['cid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whfrj_products', type_='foreignkey')
    op.drop_column('whfrj_products', 'specifications')
    op.drop_table('wfhrj_wxtoken')
    # ### end Alembic commands ###
